version: '3.5'

services:
  db_auth:
    container_name: db_api
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root1
      - POSTGRES_USER=admin1
    image: postgres:15.3-alpine